#create secret
---
apiVersion: v1
kind: Secret
metadata:
  name: nexus-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: >-
    ewogICAgImF1dGhzIjogewogICAgICAibmQuYmVnb2luZ2Rldi5tZSI6IHsKICAgICAgICAidXNlcm5hbWUiOiAiZG9ja2VyLXJlcG8iLAogICAgICAgICJwYXNzd29yZCI6ICIxMjMiLAogICAgICAgICJlbWFpbCI6ICJkb2NrZXJAZ21haWwuY29tIiwKICAgICAgICAiYXV0aCI6ICJaRzlqYTJWeUxYSmxjRzg2TVRJeiIKICAgICAgfQogICAgfQogICB9
---
#creat deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
        app: nexus-app
  template:
    metadata:
      labels:
        app: nexus-app
    spec:
      imagePullSecrets:
        - name: nexus-secret
      containers:
        - name: reactjs-cont
          image: nd.begoingdev.me/react-thy-img:1.0.0
          ports:
           - containerPort: 80
---
#creat Service
apiVersion: v1
kind: Service
metadata: 
  name: nexus-service
spec:
  type: NodePort
  selector: 
    app: nexus-app
  ports: 
    - port: 80
      targetPort: 80
      nodePort: 30001


