---
# create secret for the deployment 
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: postgres
type: Opaque
#data: 
  # POSTGRES_PASSWORD: MTIzNDU2Nzg=
  # MTIzNDU2Nzg= > echo -n 12345678 | base64
stringData:   
  POSTGRES_PASSWORD: "12345678"
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: postgres-deployment 
  namespace: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-app 
  template:
    metadata:
      labels:
        app: postgres-app
    spec:
      containers: 
        - name: postgres-cont 
          image: postgres:16
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret
---
#create service to access the deployment
apiVersion: v1 
kind: Service
metadata:
  name: postgres-svc 
  namespace: postgres
spec:
  type: NodePort
  selector:
    app: postgres-app  
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30007