apiVersion: v1
kind: Pod
metadata:
  name: maven-pod
  labels:
    app: maven
spec:
  containers:
    - name: mavenjs-docker-hub-cont
      image: nunsomrithy/springimg:v1
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dockerjs-maven-svc
spec:
  type: NodePort
  selector:
    app: maven  # Matching the label selector to select the Pod
  ports:
    - protocol: TCP
      port: 3005  # Port in the service should match the port in the pod
      targetPort: 8080
      nodePort: 30003