apiVersion: v1
kind: Pod
metadata:
  name: next-pod
  labels:
    app: next
spec:
  containers:
    - name: nextjs-docker-hub-cont
      image: nunsomrithy/nextjs:v1
      ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: dockerjs-next-svc
spec:
  type: NodePort
  selector:
    app: next  # Matching the label selector to select the Pod
  ports:
    - protocol: TCP
      port: 3003  # Port in the service should match the port in the pod
      targetPort: 3000
      nodePort: 30002