apiVersion: v1
kind: Pod
metadata:
  name: reactjs-pod
  labels:
    app: react
spec:
  containers:
    - name: reactjs-docker-hub-cont
      image: nunsomrithy/react-thy-img:v1
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dockerjs-react-svc
spec:
  replicas: 3
  type: NodePort
  selector:
    app: react  # Matching the label selector to select the Pod
  ports:
    - protocol: TCP
      port: 3000  # Port in the service should match the port in the pod
      targetPort: 80
      nodePort: 30001 