# Pods
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: react-replica
  labels:
    app: reactjs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reactjs
  template:
    metadata:
      labels:
        app: reactjs
    spec:
      containers:
        - name: react-from-dockerhub
          image: nunsomrithy/react-thy-img:v1
          ports:
            - containerPort: 80

# Create a service for the replicas
---
apiVersion: v1
kind: Service
metadata:
  name: react-svc
spec:
  type: NodePort
  selector:
    app: reactjs
  ports:
    - protocol: TCP
      port: 3009  # Port in the service should match the port in the pod
      targetPort: 80
      nodePort: 30005
