apiVersion: v1
kind: ConfigMap
metadata:
 name: index-configmap
data:
 index.html: |-  
   <!DOCTYPE html>
     <html>
      <head>
        <title>My Simple HTML Page</title>
      </head>
      <body>
       <h1>Welcome to DARA</h1>
         <p>This is a simple HTML page.</p>
       <ul>
         <li>Item 1</li>
         <li>Item 2</li>
         <li>Item 3</li>
       </ul>
      </body>
     </html>

--- 
apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-deployment
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers: 
        - name: nginx-cont 
          image: nginx:latest 
          ports:
            - containerPort: 80
          volumeMounts:
            - name: my-vol 
              mountPath: /usr/share/nginx
      volumes:
        - name: my-vol 
          configMap:
            name: index-configmap
            items:
              - key: index.html
                path: html/index.html
--- 
apiVersion: v1
kind: Service
metadata: 
  name: nginx-svc
spec:
  type: NodePort
  selector: 
    app: nginx-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008