# create configMap for postgres password 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap 
data:
  password: "12345678"

--- 
# create deployment for postgres
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-app
  template: 
    metadata:
      labels:
        app: postgres-app
    spec: 
      containers: 
      - name: postgres-cont 
        image: postgres:16
        ports: 
          - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            valueFrom: 
              configMapKeyRef:
                name: postgres-configmap
                key: password 
--- 
# create service for postgres
apiVersion: v1
kind: Service
metadata: 
  name: postgres-svc
spec:
  type: NodePort
  selector: 
    app: postgres-app
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30007