apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec: 
  replicas: {{.Values.repicasCount}}
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: spring-container
          image: 69966/springgradleimg:1.1.1
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: my-volume
              mountPath: /app/src/main/resources/images
      volumes:
        - name: my-volume
          nfs:
            server: 10.184.0.4
            path: /opt/nfs/data

